### ISSUE TITLE
Outdated URL for latest release

### ISSUE THREAD

**Issue by heidihoward** [pmer/tla-bin#14]
It seems that as of December 2020 https://tla.msr-inria.inria.fr/tlatoolbox/dist/tla2tools.jar is no longer being updated. https://github.com/tlaplus/tlaplus/releases/latest/download/tla2tools.jar should work instead
https://github.com/pmer/tla-bin/blob/1f87bc718bf732527ce89005537a4b7c5d8eb63a/download_or_update_tla.sh#L40

**Comment by danielmai** [comment]
Thanks for the report @heidihoward. #15 should fix this.
