### ISSUE TITLE
Heads up, tla.zip will be gone in next 1.5.8 release

### ISSUE THREAD

**Issue by lemmy** [pmer/tla-bin#2]
https://github.com/pmer/tla-bin/blob/f2e1d4cfd40c25616c2112b89e828aa35d9a4e8f/download_or_update_tla.sh#L55

tla.zip has already been removed in the [ci builds](https://tla.msr-inria.inria.fr/tlatoolbox/ci/dist/)

**Comment by pmer** [comment]
Thanks for the heads up!

**Comment by lemmy** [comment]
I suggest to simply switch to https://tla.msr-inria.inria.fr/tlatoolbox/dist/tla2tools.jar which has already been present in the past.

By the way, tla2tools.jar declares tlc2.TLC as the main-class in its manifest.  On Linux and macOS - if the executable bit is set - one no longer has to type ```java -cp .../tla2toos.jar ....```.   Instead ```tla2tools.jar ...``` will also work.

**Comment by pmer** [comment]
@lemmy Thanks for reporting this. We now fetch tla2toosl.jar.

Regarding setting the executable bit on tla2tools.jar, on macOS, I am familiar with how doing that allows one to double-click a JAR file and it Finder will Java will start. Is there a way to do something similar when the JAR is started from bash?

**Comment by lemmy** [comment]
Not sure I understand the question.  E.g. which spec/model is TLC supposed to check if tla2tools.jar gets double-clicked?

**Comment by pmer** [comment]
Sorry for the confusion.

What do you mean with this:

    On Linux and macOS - if the executable bit is set - one no longer has to type java -cp .../tla2toos.jar ..... Instead tla2tools.jar ... will also work.

**Comment by lemmy** [comment]
What I'm essentially saying is that the script https://github.com/pmer/tla-bin/blob/master/bin/tlc will be more or less obsolete on macOS and Linux.  To run TLC on spec A.tla, one simply calls:

```
/path/to/tla2tools.jar /path/to/spec/A.tla
```

If one creates a symlink tlc to /path/to/tla2tools.jar in /usr/local/bin/, it even becomes:

```
markus@avocado:~$ ls -lah /usr/local/bin/tlc 
lrwxrwxrwx 1 root root 30 Mär 21 09:18 /usr/local/bin/tlc -> /opt/TLA+Toolbox/tla2tools.jar
markus@avocado:~$ tlc /home/markus/src/TLA/models/mine/PageQueue/PageQueue.toolbox/Model_1/MC.tla
TLC2 Version 2.13 of 18 July 2018 (rev: 3b8859d)
Running breadth-first search Model-Checking with fp 50 and seed 1898639313971179797 with 1 worker on 4 cores with 5964MB heap and 64MB offheap memory [pid: 7564] (Linux 4.18.0-16-generic amd64, Oracle Corporation 11.0.2 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/Model_1/MC.tla
Parsing file /home/markus/src/TLA/_specs/models/mine/PageQueue/PageQueue.toolbox/Model_1/PageQueue.tla
Parsing file /tmp/TLC.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Naturals.tla
Semantic processing of module Naturals
Semantic processing of module Integers
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module PageQueue
Semantic processing of module TLC
Semantic processing of module MC
Starting... (2019-03-21 09:23:12)
Implied-temporal checking--satisfiability problem has 3 branches.
Computing initial states...
Computed 2 initial states...
Computed 4 initial states...
Finished computing initial states: 5 distinct states generated at 2019-03-21 09:23:12.
Progress(53) at 2019-03-21 09:23:13: 310 states generated, 265 distinct states found, 0 states left on queue.
Checking 3 branches of temporal properties for the complete state space with 795 total distinct states at (2019-03-21 09:23:13)
Finished checking temporal properties in 00s at 2019-03-21 09:23:13
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 6.5E-16
310 states generated, 265 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 53.
The average outdegree of the complete state graph is 1 (minimum is 0, the maximum 2 and the 95th percentile is 2).
Finished in 00s at (2019-03-21 09:23:13)
```

Unfortunately, it's not trivial to provide the same for ```SANY``` and ```pcal```.

**Comment by pmer** [comment]
Thanks. May I ask what your environment is? I'm having trouble reproducing that on either macOS 10.14 or Debian 9.

E.g., here is Debian:

```
$ chmod +x tla2tools.jar
$ ./tla2tools.jar
./tla2tools.jar: line 1: $'PK\003\004': command not found
./tla2tools.jar: line 2: $'\b\2271tN': command not found
./tla2tools.jar: line 31tNw]5META-INF/MANIFEST.MFmQN0G?Iֹ-: No such file or directory
```

**Comment by pmer** [comment]
One thing we can do is add a shebang to the top of the jar file.

```
$ echo '#!/usr/bin/java -jar' > foo.jar
$ cat tla2tools.jar >> foo.jar
$ chmod +x foo.jar
$ ./foo.jar
TLC2 Version 2.13 of 18 July 2018 (rev: 3b8859d)
Error: Error: Missing input TLA+ module.
Usage: java tlc2.TLC [-option] inputfile
```

But as you point out, the jar's main class is tlc2.TLC, and that's contained inside the manifest.

One option is to convert the /usr/local/bin/tlc to the symbolic link and leave the pcal and sany scripts using the classpath, but then we have non-uniformity between the launchers and that's a bit confusing.

**Comment by lemmy** [comment]
```
markus@avocado:~$ java -version
java version "11.0.2" 2019-01-15 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)
markus@avocado:~$ uname -a
Linux avocado 4.18.0-16-generic #17~18.04.1-Ubuntu SMP Tue Feb 12 13:35:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

Unfortunately, ```$0``` is not directly passed to Java's main method.  If it would, main could simply evaluate the name of the symlink and redirect to either TLC, SANY, or pcal.  It seems to be possible on Linux (reading from /proc/...) and might be on macOS, but generally I'm inclined to argue that we don't need symmetry here.  Most users will just want tlc.

**Comment by pmer** [comment]
Fair enough. :) Okay, let's convert tlc to a symbolic link.
