### ISSUE TITLE
Unable to run tlc 

### ISSUE THREAD

**Issue by bekiroguzhan** [pmer/tla-bin#5]
Hi, 
I am trying to run the model checker from command line. It gives error on the cfg file. Can you please help with this? 

Best

\* Add statements after this line.
\* CONSTANT definitions
CONSTANT
F <- 1
\* CONSTANT definitions
CONSTANT
N <- 4
\* CONSTANT definitions
CONSTANT
INPUT <- <<1,1,1,1>>
\* CONSTANT definitions
CONSTANT
MAXROUND <- 10
\* SPECIFICATION definition
SPECIFICATION
Spec
\* INVARIANT definition
INVARIANT
Agreement
\* PROPERTY definition
PROPERTY
BaitProgress
PROPERTY
MinorityReport
PROPERTY
Progress

**Comment by pmer** [comment]
Hi bekiroguzhan, this is probably a question for tlc. The tla-bin script itself is just a convenience script to run tlc. I recommend you reach out to the TLA+ community with this question as they will probably be able to answer.

https://groups.google.com/forum/?fromgroups#!forum/tlaplus

Hope this helps.
