### ISSUE TITLE
pcal command fails if no pcal code found

### ISSUE THREAD

**Issue by ToddG** [pmer/tla-bin#7]
**SUMMARY**
`tlc` depends on `pcal` successfully running and generating the `.cfg` file. However, if the input file is just tla+ and does not contain the pluscal comment block, `pcal` fails. 

**EXPECTED**
I'd expect `pcal` to succeed _and_ generate the .cfg file even if no pluscal code is found.

**REPRO**

```
git clone https://github.com/tlaplus/Examples.git examples
cd examples/specifications/N-Queens
pcal Queens
```

**ERROR A**
```
ls
QueensPluscal.tla  QueensPluscal.toolbox  Queens.tla  Queens.toolbox  README  states

pcal Queens
pcal.trans Version 1.9 of 10 July 2019

Unrecoverable error:
 -- Beginning of algorithm string --algorithm not found..
```

This seems ok, except that I'd like to run `tlc` on this, too:

**ERROR B**

```
tlc Queens

TLC2 Version 2.14 of 10 July 2019 (rev: 0cae24f)
Running breadth-first search Model-Checking with fp 36 and seed 408714217296578281 with 1 worker on 8 cores with 7134MB heap and 64MB offheap memory [pid: 19015] (Linux 4.15.0-96-generic amd64, Ubuntu 11.0.6 x86_64, MSBDiskFPSet, DiskStateQueue).
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a tlc2.tool.ConfigFileException
: TLC encountered the following error when trying to read the configuration file Queens.cfg:
File not found.
Finished in 00s at (2020-04-16 13:56:29)
```

**Comment by pmer** [comment]
That makes sense. Thanks for the writeup.

This might be an issue you can report upstream to TLA+, too, at https://github.com/tlaplus/tlaplus. I wonder if there is a reason why the underlying `pcal` translator fails when it has no work to do, and why it's doesn't continue to create the `.cfg` file.

Alternatively, there may be another way to generate the `.cfg` file if `pcal` fails. Just thinking about ways it might be solved.

Regardless, users of tla-bin shouldn't have to worry about this behavior and it should just work.

**Comment by pmer** [comment]
Closing this issue as stale. Please reopen it if you continue to experience any issues.
